class DeviceConstants {
  static const Map<String, List<String>> namePatterns = {
    'Samsung': [
      'Galaxy_####',
      'SM-####',
      'GalaxyS##',
      'GalaxyA##',
      'SM-A###',
      'SM-G###',
      'Galaxy A##',
      'Galaxy S##',
      'Galaxy M##',
      'Galaxy F##',
      'AndroidAP_####',
    ],
    'Xiaomi': [
      'Xiaomi_####',
      'Redmi_####',
      'POCO_####',
      'Mi_####',
      'Redmi Note ##',
      'POCO X#',
      'POCO F#',
      'POCO M#',
      'Redmi ##',
      'Mi ##',
      'AndroidAP_####',
    ],
    'Oppo': [
      'OPPO_####',
      'CPH####',
      'OPPO A##',
      'OPPO Reno#',
      'OPPO Find X#',
      'CPH###',
      'AndroidAP_####',
    ],
    'Vivo': [
      'vivo_####',
      'vivo Y##',
      'vivo V##',
      'vivo X##',
      'iQOO_####',
      'iQOO ##',
      'AndroidAP_####',
    ],
    'Realme': [
      'realme_####',
      'RMX####',
      'realme ##',
      'realme C##',
      'realme GT#',
      'Narzo ##',
      'AndroidAP_####',
    ],
    'Huawei': [
      'HUAWEI_####',
      'HUAWEI-####',
      'HUAWEI P##',
      'HUAWEI Y#',
      'HONOR_####',
      'HONOR ##',
      'AndroidAP_####',
    ],
    'iPhone': [
      'iPhone_####',
      "iPhone's iPhone",
      'iPhone (##)',
      'My iPhone',
      'iPhone',
    ],
    'Router': [
      'NETGEAR##',
      'NETGEAR####',
      'ASUS_####',
      'ASUS##',
      'TP-Link_####',
      'TPLink####',
      'Linksys####',
      'Linksys_####',
      'D-Link_####',
      'DLink####',
      'Wireless_####',
      'Router_####',
      'Network_####',
      'Home_WiFi_####',
      'Tenda_####',
      'Tenda##',
      'Mercusys_####',
      'ZTE_####',
      'ZTE####',
      'Huawei_####',
      'HuaweiWiFi_####',
      'Belkin_####',
      'Belkin##',
      'Cisco_####',
      'Arris_####',
      'Motorola_####',
      'Ubiquiti_####',
      'MikroTik_####',
      'Synology_####',
      'Buffalo_####',
      'AirPort_####',
      'Archer_####',
      'Archer##',
      'Deco_####',
      'Mesh_####',
      'SmartWiFi_####',
      'HomeNet_####',
      'MyNetwork_####',
      'WiFi_####',
      'Net_####',
    ],
  };

  static List<String> get categories => ['Random', ...namePatterns.keys];
}
